Avoids using a symlink to the lib directory to avoid conflict with the Artix filesystem package.
Kangie/plymouth-openrc-plugin pull request #1
Opened 2022-03-08 22:39 UTC by Stev18

Changes /lib/ to /usr/lib/ in the Makefile to prevent a conflict with Artix's filesystem package which owns /lib.

2022-05-13 14:58 UTC, Kangie commented
Whoops, I missed this PR entirely. I'll review it this weekend. :)

2024-02-20 11:49 UTC, NyaomiDEV commented
Any update on this?

2024-02-20 21:36 UTC, eli-schwartz requested changes

2024-02-20 21:36 UTC, eli-schwartz commented on Makefile
> +PLUGINS_PATH := $(DESTDIR)/usr/lib/rc/plugins
This changes one form of breakage for another.

It doesn't respect https://www.gnu.org/prep/standards/html_node/Directory-Variables.html which should be used to define prefix / libdir. That is the only valid solution -- of course ultimately it should be ported to a real build system. :D

2024-06-29 13:25 UTC, Kangie commented
Fixed properly in https://github.com/Kangie/plymouth-openrc-plugin/commit/c7f771b7416ab656caf8a4166cfcdf79b19aae86 - expect a new release once I get the kinks ironed out of CI.

2024-06-29 13:25 UTC, closed without merging